image: python:3.10.8

stages:
  - linting
  - testing
  - deploy

before_script:
  - apt-get update
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - export VENV_HOME_DIR=$(pipenv --venv)
  - source $VENV_HOME_DIR/bin/activate

imports ordering:
  stage: linting
  interruptible: true
  script:
    - isort . --check-only --profile black

style checks:
  stage: linting
  interruptible: true
  script:
    - flake8 --max-line-length=88 --extend-ignore=E203,E501 .

type checks:
  stage: linting
  interruptible: true
  script:
    - mypy app/* --ignore-missing-imports

format checks:
  stage: linting
  interruptible: true
  script:
    - black . --check

unit tests:
  stage: testing
  interruptible: true
  script:
    - pytest --junitxml=report.xml --cov=app/ --cov-report term-missing tests/
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  before_script: []
  script:
    - echo python --version
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml