steps:
    # Build the container image (image name: foodsnap-backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/foodsnap-backend', '.' ]
    # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/foodsnap-backend']
    # Deploy to Cloud Run (service name: foodsnap-backend)
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'foodsnap-backend', '--image', 'gcr.io/$PROJECT_ID/foodsnap-backend', '--region', 'europe-west2', '--no-allow-unauthenticated']